services:
  server:
    build:
      context: .
    environment:
      TZ: UTC
    ports:
      - 3333:3333
    command: ["bun", "server.ts"]
  workers:
    build:
      context: .
    environment:
      TZ: UTC
    command: ["bun", "background.ts"]
    deploy:
      mode: replicated
      replicas: 5
